### ISSUE TITLE
Need to develop a MHz .wav file.

### ISSUE THREAD

**Issue by peterstivin** [lowbyteproductions/Making-WAVs#1]

**Comment by peterstivin** [comment]
Closing the issue.

**Comment by francisrstokes** [comment]
I guess you figured it out already, but the sample rate can be any unsigned 32-bit number. That gives you a maximum of 4294967295 samples per second, or ~4.29 GHz. You don't need to go anywhere near that high - the Nyquist rate for your maximum frequency would be 12MHz, so you could plug in `12000000` and represent the signal comfortably.
